name: Student Link deploy

on:
  push:
    branches:
      - master
      - fr-*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, build, and deploy
      run: |
        npm run site-build
        git config --global user.name "GITHUB CI"
        git config --global user.email "ci@studentlink.co.za"
        npm run quick-gh
      env:
        CI: true
